AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'

Layout/TrailingWhitespace:
  Enabled: true

Layout/EndAlignment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
